# Generated by Django 5.2.15 on 2026-06-29 09:54

from django.db import migrations

def create_token_packages(apps, schema_editor):
    TokenPackage = apps.get_model("billing", "TokenPackage")

    packages = [
        {
            "name": "Старт",
            "slug": "start",
            "tokens_amount": 41_000_000,
            "price_rub": 150,
            "description": "Для тестов, pet-проектов и первых API-запросов.",
            "is_popular": False,
            "sort_order": 1,
        },
        {
            "name": "База",
            "slug": "base",
            "tokens_amount": 186_000_000,
            "price_rub": 600,
            "description": "Оптимальный пакет для небольших проектов.",
            "is_popular": True,
            "sort_order": 2,
        },
        {
            "name": "Pro",
            "slug": "pro",
            "tokens_amount": 1_100_000_000,
            "price_rub": 3000,
            "description": "Для активного использования API и production-проектов.",
            "is_popular": False,
            "sort_order": 3,
        },
    ]

    for package in packages:
        TokenPackage.objects.update_or_create(
            slug=package["slug"],
            defaults=package,
        )


def delete_token_packages(apps, schema_editor):
    TokenPackage = apps.get_model("billing", "TokenPackage")
    TokenPackage.objects.filter(slug__in=["start", "base", "pro"]).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_tokenpackage_payment_balancetransaction'),
    ]

    operations = [
        migrations.RunPython(create_token_packages, delete_token_packages),
    ]
