# Generated by Django 5.2.15 on 2026-06-29 10:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_seed_token_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rub_per_1m_tokens', models.DecimalField(decimal_places=2, default=Decimal('2.45'), help_text='Цена за 1 миллион токенов в рублях.', max_digits=10)),
                ('usd_to_rub_rate', models.DecimalField(decimal_places=2, default=Decimal('90.00'), help_text='Курс USD/RUB для крипто-платежей.', max_digits=10)),
                ('min_custom_million_tokens', models.PositiveIntegerField(default=10, help_text='Минимальное custom-пополнение в миллионах токенов.')),
                ('max_custom_million_tokens', models.PositiveIntegerField(default=5000, help_text='Максимальное custom-пополнение в миллионах токенов.')),
                ('is_custom_topup_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing settings',
                'verbose_name_plural': 'Billing settings',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('package', 'Package'), ('custom', 'Custom amount')], default='package', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_rub',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.tokenpackage'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock'), ('sbp', 'SBP'), ('cards', 'Cards'), ('cryptobot', 'CryptoBot'), ('yookassa', 'YooKassa')], default='mock', max_length=50),
        ),
    ]
