# Generated by Django 5.2.15 on 2026-06-29 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_name', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('provider_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('request_tokens', models.PositiveIntegerField(default=0)),
                ('response_tokens', models.PositiveIntegerField(default=0)),
                ('charged_tokens', models.PositiveIntegerField(default=0)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
